name: Deploy XRPL metadata

on:
  push:
    branches:
      - main

jobs:
  boostrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create build directory
        run:  mkdir build

      - run: ls