name: Deploy XRPL Metadata

on:
  push:
    branches:
      - main

jobs:
  boostrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create build directory
        run:  mkdir build

      - name: Create metadata destination directory
        run:  mkdir build/.well-known

      - name: Copy metadata into target directory
        run:  cp ./meta.toml build/.well-known/xrpl-ledger.toml

      - name: Configure domain CNAME
        run:  echo "xrp.services.xnet.cam" >> build/CNAME

      - name: Configure Jekyll
        run:  echo "" >> build/.nojekyll

      - name: Deploy artefact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: boostrap

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy artefact
        uses: actions/deploy-pages@v2
