name: Automatically close opened PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose PR
        uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            We don't accept pull requests for this repository.
            For Enquiries or requests for amendment, please contact the XNET team members directly.

            This pull request will be closed.
